spring:
  application:
    name: my-spring-application

  # Configuration => H2
  datasource:
    url: jdbc:h2:mem:pedro_db
    driver-class-name: org.h2.Driver
    username: pedrocros
    password: 123456

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
